server:
  port: 8081
spring:
  application:
    name: MyBlog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dictdb?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2b8&allowMultiQueries=true
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 30000ms
    database: 15
mybatis:
  mapper-locations:
    - classpath:/mappers/*.xml
logging:
  level:
    com.zxj.blog: debug
  pattern:
    console: "%d - %msg%n"
    #    console: "%d{yyyy-MM-dd HH:mm:ss,SSS} [%t] [%c]-[%p] ============> :%msg%n"
#ES相关配置
ES:
  host: localhost
  port: 9200